version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: warehouse_control_development
      POSTGRES_USER: warehouse_admin
      POSTGRES_PASSWORD: warehouse_pass
    ports:
      - "5433:5432"
  web:
    build: .
    command: rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/warehouse_control
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_NAME: warehouse_control_development
      DB_USERNAME: warehouse_admin
      DB_PASSWORD: warehouse_pass
      RAILS_ENV: development
    stdin_open: true
    tty: true

networks:
  default:
    name: myapp_default
